version: "3"

services:

  # This was just for testing docker, left it for reference

  flask:
    restart: always
    build: ./flask
    volumes:
      - ./flask:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - db


# This is my actual stuff i use to run the website:

  web:
    image: ebiven/vue-cli
    build: ./vue_test
    ports:
      - 8080:8080
    command: sh -c "npm install && npm run dev"
    volumes:
      - "./vue_test:/app"
    environment:
      HOST: 0.0.0.0
    depends_on:
      - flask

  db:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5002:80

